// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 28
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){








var xb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var yb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,zb=function(a){if(null==a)return String(a);var b=yb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ab=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},za=function(a){if(!a||"object"!=zb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ab(a,"constructor")&&!Ab(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ab(a,b)},V=function(a,b){var c=b||("array"==zb(a)?[]:{}),d;for(d in a)if(Ab(a,d)){var e=a[d];"array"==zb(e)?("array"!=zb(c[d])&&(c[d]=[]),c[d]=V(e,c[d])):za(e)?(za(c[d])||(c[d]={}),c[d]=V(e,c[d])):c[d]=e}return c};var fb=null,Bb=Math.random(),Cb=null,pa=null,Ma=!1,Db={},Eb={},Na={};var Oa,Pa,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,
Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df;
(function(){var a=function(a){return{toString:function(){return a}}};Fb=a("");Gb=a("0");Hb="";Ib=a("");Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("2");Rb=a("3");Sb=a("");Tb=a("");Ub=a("");
Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");
ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("4");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");
Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("5");Gc=a("");Hc=a("6");Ic=a("");Jc=a("7");Kc=a("");Lc=a("");Mc=a("8");Nc=a("");Oc=a("");Pc=a("");Qc=a("");
Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("9");Wc=a("");Xc=a("10");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("11");ed=a("");fd=a("");
gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");od=a("12");pd=a("");qd=a("");Oa=a("13");rd=a("");sd=a("23");td=a("24");ud=a("");vd=a("");
xd=a("");yd=a("14");zd=a("");Ad=a("");Bd=a("");Cd=a("");Pa=a("15");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("16");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("17");Od=a("");Pd=a("");
Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("18");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");
je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");
Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("20");Re=
a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");
hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf="";of=a("");pf=a("");qf=a("");rf=a("");sf=a("");tf=a("21");uf=a("");vf=a("");wf=a("");xf=a("");yf=a("");zf=
a("22");Af=a("");Bf=a("");Cf=a("");Df=a("")})();var wb=function(a,b){V(a,b)},qb=function(){},T=function(a){return"function"==typeof a},cb=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Ef=function(a){return"number"==zb(a)&&!isNaN(a)},Ff=function(a){return/^[0-9]+$/.test(a)},ub=function(a){return"string"==zb(a)},vb=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},oa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},
W=function(a){return Math.round(Number(a))||0},Ca=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Gf=function(a){var b=[];if(cb(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},I=function(){return new Date},va=function(a,b){if(!Ef(a)||!Ef(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Hf=function(){this.prefix="gtm.";this.values={}};Hf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Hf.prototype.get=function(a){return this.values[this.prefix+a]};Hf.prototype.contains=function(a){return void 0!==this.get(a)};
var If=function(a,b,c){try{if(!a[Sd])return a[Oa](a,b||qb,c||qb);c&&c()}catch(d){}return!1},Lf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=oa(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Mf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Nf=function(a){return function(){return a("GTM-TP5WBG")}},Of=function(a){for(var b=0;b<a.length;b++)a[b]()},ya=function(){return"gtm"+Pf()},
Pf=function(){var a=fb.sequence||0;fb.sequence=a+1;return a},Aa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Qf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Rf=function(a,b){0==b?a.rb=!0:a.ca=!0;var c=a.h;a.B&&(a.B.Ta[c]=b);Db[c]&&(Db[c].state=b)},Sf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var B=window,P=document,Uf=navigator,La=function(a,b){var c=B[a];B[a]=void 0===c?b:c;return B[a]},O=function(a,b,c,d){return(d||"http:"!=B.location.protocol?a:b)+c},Vf=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},kb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},t=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;kb(d,b);c&&(d.onerror=c);Vf(d);return d},ia=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Vf(c);kb(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},Q=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},ha=function(a,b,c){a.removeEventListener?
a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},u=function(a){B.setTimeout(a,0)},mb=!1,nb=[],Wf=function(a){if(!mb){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){mb=!0;for(var e=0;e<nb.length;e++)u(nb[e])}nb.push=function(){for(var a=0;a<arguments.length;a++)u(arguments[a]);return 0}}},Xf=0,Yf=function(){if(!mb&&140>Xf){Xf++;try{P.documentElement.doScroll("left"),Wf()}catch(a){B.setTimeout(Yf,50)}}},
ka=function(a){var b=P.getElementById(a);if(b&&ma(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ma(document.all[a][c],"id")==a)return document.all[a][c];return b},ma=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},ab=function(a){return a.target||a.srcElement||{}},na=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},tb=function(a){var b=P.createElement("div");
b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},bb=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;var e=a;for(d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Zf=!1,$f=[],ag=function(){if(!Zf){Zf=!0;for(var a=0;a<$f.length;a++)u($f[a])}},bg=function(a){a=a||B;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},rb=function(a){window.console&&
window.console.log&&window.console.log(a)};var ta=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||B.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||B.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:B.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=vb(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},sa=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},
ra=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var Ea=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=ta(ra(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var S=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},hb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},xa=function(a,b){V(a,b)},Da=function(a){return W(a)};var ja=function(a){var b=P;return cg?b.querySelectorAll(a):null},dg=!1;if(P.querySelectorAll)try{var eg=P.querySelectorAll(":root");eg&&1==eg.length&&eg[0]==P.documentElement&&(dg=!0)}catch(a){}var cg=dg;var fg=new Hf,gg={},ig={set:function(a,b){V(hg(a,b),gg)},get:function(a){return Y(a,2)},reset:function(){fg=new Hf;gg={}}},Y=function(a,b){var c;if(2!=b)c=fg.get(a);else a:{var d=a.split("."),e=0;var g=gg;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}return c};var kg=function(a,b){fg.set(a,b);V(hg(a,b),gg)},hg=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var og=!1,pg=!1;var qg=Math.random(),rg="0.050000">qg;
var sg=function(a,b){if(rg){var c="//www.googletagmanager.com/a?id=GTM-TP5WBG&cv=28",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",I().getTime()-W(Cb));c+="&sr=0.050000";d("&ps=",qg);d("&cb=",va());F(c)}},tg=qb,ug=function(){var a=!1;};var wg=function(a){var b=fb.zones;return b?b.checkState("GTM-TP5WBG",a):vg},vg={active:!0,isWhitelisted:function(){return!0}};var yg=qb,zg=[],Ag=!1,ea=function(a){return B["dataLayer"].push(a)},Bg=function(a){var b=!1;return function(){!b&&T(a)&&u(Nf(a));b=!0}},Kg=function(){for(var a=!1;!Ag&&0<zg.length;){Ag=!0;var b=zg.shift();if(T(b))try{b.call(ig)}catch(zc){}else if(cb(b))a:{var c=b;if(ub(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=gg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(zc){}}}else{var p=void 0,v=void 0,x=b;var r=x._clear;for(v in x)if(x.hasOwnProperty(v)){kg(v,x[v])}var A=!1,C=x.event;if(C){x.hasOwnProperty("gtm.uniqueEventId")||
(x["gtm.uniqueEventId"]=Pf(),kg("gtm.uniqueEventId",x["gtm.uniqueEventId"]));p=x["gtm.uniqueEventId"];pa=C;var w=wg(p);if(w.active){var y=Bg(x.eventCallback),J=x.eventTimeout;J&&B.setTimeout(y,Number(J));A=yg(p,C,w.isWhitelisted,y,x.eventReporter)}}Cb||(Cb=x["gtm.start"])&&tg();var K,E=x,D=p,H=C,N=gg;pa=null;a=A||a}Ag=!1}return!a},Lg=function(){var a=Kg();try{var b=B["dataLayer"].hide;if(b&&void 0!==b["GTM-TP5WBG"]&&b.end){b["GTM-TP5WBG"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},
Mg=function(){var a=La("dataLayer",[]),b=La("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};nb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});$f.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(zg.push.apply(zg,b);300<this.length;)this.shift();return Kg()};zg.push.apply(zg,a.slice(0));u(Lg)};var Sa,Sg,Tg,Ya=/(Firefox\D28\D)/g.test(Uf.userAgent),Vg=function(a,b){return function(c){c=c||B.event;var d=ab(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=bb(d,["a","area"]),e=!d||!d.href||Ug(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Sa:Tg;if(c.defaultPrevented||!1===c.returnValue||c.ha&&c.ha()){if(d){var g={simulateDefault:!1},h=Ta(f,["wnc","nwnc"]);h&&Ua(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=Ta(f,
["wnc","nwnc","nwc","wc"]);(k=Ua(a,d,g,f.wt,l))||(Va(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Ya;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Za(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Ua=function(a,b,c,d,e){var f=d||2E3,g=Wg(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=Xg(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=Yg(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return ea(g)},Xa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Za=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Uf.userAgent),e=Xa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=B.frames&&B.frames[f]||B[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+I().getTime(),b.targetWindow=B.open("",b.targetWindowName));break;default:d&&!B.frames[e]?(b.simulateDefault=!1,c=!0):(B.frames[e]||(b.targetWindowName=e),b.targetWindow=B.frames[e]||B.open("",e))}return c},Xg=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||I().getTime(),500>I().getTime()-c&&B.setTimeout(Xg(a,
b,c),25)))}},Yg=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;Wa(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||I().getTime(),500>I().getTime()-c&&B.setTimeout(Yg(a,b,c),25)}},Ta=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Zg=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;
f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Va=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<$g.length;c++)if(a.passingRules[c]){var d=ah[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=$g[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},ua=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=ab(a);b&&
Ua("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Sg&&(Sg=sa(P.location));Zg(Tg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;P.gtmHasLinkClickListenerTag=!0;f="click";g=Vg(a,b||!1);break;case "FORM_SUBMIT":Zg(Sa,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=Vg(a,b||!1);break;default:return}Q(P,f,g,h)},Ug=function(a){if(!Sg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ra(a);return Sg==sa(c)},Wa=function(a){try{if(a.constructor&&
a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit},Wg=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||ma(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};switch(b){case "LINK_CLICK":c["gtm.elementUrl"]=
a.href;break;case "FORM_SUBMIT":var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d;break;default:c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||""}return c},bh=function(){var a=function(a){var b=La("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Tg=a("linkClickMap");Sa=a("formSubmitMap")};var $a=function(a,b,c){Q(a,b,c,void 0)},fa=function(a,b){return B.setTimeout(a,b)},ca=function(a,b,c){t(a,b,c)},Ra={},Fa=function(a,b,c){var d=Ra[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.sb:a.hb,d=0;d<c.length;d++)B.setTimeout(c[d],0)}};d={status:1,sb:[],hb:[],sc:void 0};d.bd=t(a,e(d,2),e(d,3));Ra[a]=d}0===d.status&&(d.sc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.sb.push(b),c&&d.hb.push(c))},qa=function(a,b){return Y(a,b||
2)},aa=function(a,b){B[a]=b},q=function(a,b,c){var d=B;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},z=function(a,b,c,d){return(d||"http:"!=B.location.protocol?a:b)+c},Ka=function(a,b,c,d,e){},ch=void 0,Ja=function(a){if(!ch){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<ch.length;a++)u(ch[a])})).observe(a,{childList:!0,subtree:!0});
else{var b=!1;$a(a,"DOMNodeInserted",function(){b||(b=!0,u(function(){b=!1;for(var a=0;a<ch.length;a++)u(ch[a])}))})}};ch=[];P.body?b():u(b)}ch.push(a)};var dh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),eh={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},fh={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},gh=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var Dg=function(a){var b=Y("gtm.whitelist");var c=b&&gh(Gf(b),eh),d=Y("gtm.blacklist")||Y("tagTypeBlacklist")||[];dh.test(B.location&&
B.location.hostname)&&(d=Gf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&gh(Gf(d),fh),f={};return function(g){var h=g&&g[Oa];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>vb(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>vb(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=vb(e,h.a)))a:{for(var v=h.b||[],x=new Hf,r=0;r<e.length;r++)x.set(e[r],
!0);for(r=0;r<v.length;r++)if(x.get(v[r])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _c=function(a){return a[zf]};_c.a="c";_c.b=["google"];var ih=void 0,jh="",kh=0,lh=void 0,_et=function(a){var b,c=Y("gtm.element"),d=Y("event"),e=Number(I());ih===c&&jh===d&&kh>e-250?b=lh:(lh=b=c?na(c):"",ih=c,jh=d);kh=e;return b?b:a[Pc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Y("gtm.elementUrl")||a[Pc]||""),c=ra(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return pa};_e.a="e";_e.b=["google"];var mh=/(^|\.)doubleclick\.net$/i,nh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,db=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=oa(e[0]);if(f&&f==a){var g=oa(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},oh=function(a,b,c,d,e){if(mh.test(P.location.hostname)||"/"==c&&nh.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=P.cookie;P.cookie=f;return g!=
P.cookie||0<=vb(db(a),b)},ph=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},qh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},rh=function(){var a=ta(B.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var sh=function(a,b){this.g=a;this.m=b};sh.prototype.toString=function(){var a=""+this.g;1<this.m&&(a=a+"-"+this.m);return a};var th=function(a,b){this.Ra=a;this.ta=b};th.prototype.toString=function(){return""+this.ta+"."+this.Ra};var wh=function(a,b){var c=new uh(null,a,b);vh(c);return c},uh=function(a,b,c){this.fb=Math.floor(I().getTime()/864E5);this.sa=b||"auto";this.ja=c||"/";var d=ph(this.sa),e=qh(this.ja);this.H=a||new sh(d,e);this.i=[];this.D=new Hf},yh=function(a,b,c){b&&(""==c.Ra?xh(a,b):(a.D.contains(b)||a.i.push(b),a.D.set(b,c)))},zh=function(a,b){for(var c=0;c<b.length;c++)yh(a,b[c][0],b[c][1])},xh=function(a,b){var c=vb(a.i,b);0<=c&&a.i.splice(c,1);a.D.set(b,void 0)},Ah=function(a){for(var b=[],c=0;c<a.i.length;c++){var d=
a.i[c];b.push([d,a.D.get(d)])}return b},Bh=function(a){for(var b=0,c=0;c<a.i.length;c++)b=Math.max(b,a.D.get(a.i[c]).ta);return 864E5*b};uh.prototype.toString=function(){if(0==this.i.length)return"";for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];a.push(""+c+"."+this.D.get(c).toString())}return"GAX1."+this.H.toString()+"."+a.join("!")};
var Ch=function(a,b){for(var c=new Date,d=qh(a.ja),e=[],f=0;f<a.i.length;f++){var g=a.i[f];a.D.get(g).ta<a.fb&&e.push(g)}for(f=0;f<e.length;f++)xh(a,e[f]);if(a.i.length>(b||10))return!1;c.setTime(Bh(a));if("auto"!=a.sa)return oh("_gaexp",a.toString(),a.ja,a.sa,c);for(var h=rh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.H=new sh(ph(h[k]),d),oh("_gaexp",a.toString(),a.ja,h[k],c)))return!0;return!1},vh=function(a){for(var b=a.H.g,c=a.H.m,d=db("_gaexp"),e=[],f=0;f<d.length;f++){var g=Dh(a,d[f]);g&&e.push(g)}Sf(e,
function(a,d){var e=a.H,f=d.H;return e.g==f.g&&e.m==f.m?!1:e.g==b&&e.m==c?!0:f.g==b&&f.m==c?!1:e.g==b?f.g!=b||e.m<f.m:f.g==b?!1:e.m==c?f.g!=b&&(f.m!=c||e.g<f.g):f.m==c?!1:e.g<f.g||e.g==f.g&&e.m<f.m});a.H=0<e.length?e[0].H:new sh(b,c);for(f=e.length-1;0<=f;f--)zh(a,Ah(e[f]))},Dh=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=oa(e[0]);if(0!=f.length){var g=2==e.length?oa(e[1]):"1";if(Ff(f)&&Ff(g)){d=new sh(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new uh(d,a.sa,a.ja),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Ff(m[1]))return;yh(h,m[0],new th(m[2],W(m[1])))}}return h}}};var _v=function(a){var b=Y(a[Yd].replace(/\\\./g,"."),a[Hc]);return void 0!==b?b:a[Pc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Y("gtm.referrer")||P.referrer);if(!b)return b;var c=ra(b);return b};_f.a="f";_f.b=["google"];var Hh=function(a){var b=B.location,c;(c=a[Ec]?a[Ec]:Y("gtm.url"))&&(b=ra(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[oc]&&(f=ta(b,a[oc],a[Ke],a[Oc],a[xe]));return f},_u=Hh;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[Qb]).indexOf(String(a[Rb]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[Qb])==String(a[Rb])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[Rb],a[zd]?"i":void 0)).test(a[Qb])};_re.a="re";_re.b=["google"];
var Nh=!1,Oh=[],Ph=function(a){var b=B.google_trackConversion,c=a.gtm_onFailure;T(b)?b(a)||c():c()},Qh=function(){for(;0<Oh.length;)Ph(Oh.shift())},_awct=function(a,b,c){var d={google_conversion_domain:"",google_conversion_id:a[yd],google_conversion_label:a[Id],google_conversion_value:a[zf]||0,google_remarketing_only:!1,onload_callback:b,gtm_onFailure:c};a[Dc]&&(d.google_conversion_currency=a[Dc]);a[he]&&(d.google_conversion_order_id=a[he]);Oh.push(d);Nh||(Nh=!0,t("//www.googleadservices.com/pagead/conversion_async.js",
function(){Qh();Oh={push:Ph}},function(){Qh();Nh=!1}))};_awct.a="awct";_awct.b=["google"];var eb=new String("undefined"),ob=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===eb?b:a[d]);return c.join("")}};ob.prototype.toString=function(){return this.resolve("undefined")};ob.prototype.valueOf=ob.prototype.toString;var Rh={},pb=function(a,b){var c=Pf();Rh[c]=[a,b];return c},Sh=function(a){var b=a?0:1;return function(a){var c=Rh[a];if(c&&T(c[b]))c[b]();Rh[a]=void 0}};var Th=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Uh=function(a,b){return a<b?-1:a>b?1:0};var Vh;a:{var Wh=xb.navigator;if(Wh){var Xh=Wh.userAgent;if(Xh){Vh=Xh;break a}}Vh=""}var Z=function(a){return-1!=Vh.indexOf(a)};var Yh=function(){return Z("iPhone")&&!Z("iPod")&&!Z("iPad")};var Zh=function(a){Zh[" "](a);return a};Zh[" "]=function(){};var ai=function(a,b){var c=$h;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var bi=Z("Opera"),ci=Z("Trident")||Z("MSIE"),di=Z("Edge"),ei;if(ei=Z("Gecko")){var fi=Vh.toLowerCase();ei=!(-1!=fi.indexOf("webkit")&&!Z("Edge"))}var gi=ei&&!(Z("Trident")||Z("MSIE"))&&!Z("Edge"),hi=Vh.toLowerCase(),ii=-1!=hi.indexOf("webkit")&&!Z("Edge");ii&&Z("Mobile");Z("Macintosh");Z("Windows");Z("Linux")||Z("CrOS");var ji=xb.navigator||null;ji&&(ji.appVersion||"").indexOf("X11");Z("Android");Yh();Z("iPad");Z("iPod");Yh()||Z("iPad")||Z("iPod");
var ki=function(){var a=xb.document;return a?a.documentMode:void 0},li;a:{var mi="",ni=function(){var a=Vh;if(gi)return/rv\:([^\);]+)(\)|;)/.exec(a);if(di)return/Edge\/([\d\.]+)/.exec(a);if(ci)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ii)return/WebKit\/(\S+)/.exec(a);if(bi)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ni&&(mi=ni?ni[1]:"");if(ci){var oi=ki();if(null!=oi&&oi>parseFloat(mi)){li=String(oi);break a}}li=mi}
var pi=li,$h={},qi=function(a){return ai(a,function(){for(var b=0,c=Th(String(pi)).split("."),d=Th(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Uh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Uh(0==k[2].length,0==l[2].length)||Uh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},ri;
var si=xb.document;ri=si&&ci?ki()||("CSS1Compat"==si.compatMode?parseInt(pi,10):5):void 0;var ti;if(!(ti=!gi&&!ci)){var ui;if(ui=ci)ui=9<=Number(ri);ti=ui}ti||gi&&qi("1.9.1");ci&&qi("9");var sb=function(a,b){var c="";ci&&!vi(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(wi)a.srcdoc=d;else if(xi){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else yi(a,d)},wi=ii&&"srcdoc"in document.createElement("iframe"),xi=gi||ii||ci&&qi(11),yi=function(a,b){ci&&qi(7)&&!qi(10)&&6>zi()&&Ai(b)&&(b=Bi(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};ci&&!vi(a)?Ci(a,c):c()},zi=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},vi=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Zh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Di=0,Ci=function(a,b){var c="goog_rendering_callback"+Di++;xb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Ai=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Bi=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Ti=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=Qi(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=Ri(f,g);Si(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Ui=null,Qi=function(a){if(Ui)return Ui;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Ui=
c}0==a.styleSheets.length&&a.createStyleSheet();return Ui=a.styleSheets[0]},Ri=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Si=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var aj={},bj=void 0,cj=function(a){var b=aj[a];b||(b={id:a,v:[],fa:0,Va:null,Ia:void 0,Oa:!1},aj[a]=b);bj=b},ej=function(a,b,c,d){var e=bj;if(!cg||!e)return!1;var f={id:e.id+":"+e.v.length,Bb:b,aa:[],wb:c,I:a,Ca:0,ya:d||null,cb:0,ea:!1};e.v.push(f);null===a?(f.ea=!0,b(null)):dj(e);return!0},fj=function(a){var b=Ti(a,"visibility","hidden",!0);return function(){T(b)&&b.apply();b=null}},gj=function(a,b,c,d){var e=b;if(!mb){var f=fj(a.A);nb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ej(a,
e,c,d)},dj=function(a){if(!a.Oa){for(var b=a.fa;b<a.v.length;b++){var c=a.v[b],d=b==a.fa;if(!c.ea&&!hj(d,c))break;c.ea&&d&&a.fa++}a.v.length>a.fa?(a.Va||(a.Va=B.setTimeout(function(){a.Va=null;dj(a)},80)),mb||a.Ia||(a.Ia=function(){u(function(){dj(a)})},Q(P,"DOMContentLoaded",a.Ia))):ij(a)}},ij=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.I)for(var d=ja(c.I.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(jj(f,c.id),c.aa.push(kj(f,c.id)))}}},
hj=function(a,b){var c=[];if(b.I){var d=lj(b.I,b.id),e=null;b.ya&&(e=lj(b.ya,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!mb&&(null===b.ya.s||b.cb+c.length<b.ya.s)))break;c.push({element:g,vc:h})}}if(!mb&&b.wb&&(!a||null==b.I.s||b.I.s!=b.Ca+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].vc,n;b.Ca++;jj(l,b.id);m&&(b.cb++,n=b.id+"-t",jj(m,n));var p=b.Bb(l,m);T(p)&&b.aa.push(p);b.aa.push(kj(l,b.id));m&&n&&b.aa.push(kj(m,n))}if(b.I.s&&
b.I.s==b.Ca||mb)b.ea=!0;return!0},jj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},kj=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},lj=function(a,b){for(var c=ja(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.G&&!mj(f))break;d.push(f)}}return d},mj=function(a){if(mb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ia=function(a,b){var c=b||xb,d=c.onerror,e=!1;ii&&!qi("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,line:h,Sc:k,error:l});return e}};var Hj=function(a){if(!a)return!1;if(a[Pb]&&cb(a[Rb])){for(var b=a[Rb],c=0;c<b.length;c++)if(a[Rb]=b[c],If(a))return!0;return!1}return If(a)};var dk=74,ek=[],fk=[],Eg=[],gk=new Hf,hk=[],ik=[],$g=[],ah=[],jk=function(){this.P=[]};jk.prototype.set=function(a,b){this.P.push([a,b]);return this};jk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.P.length;d++){var e=Hg(this.P[d][0],a,b),f=Hg(this.P[d][1],a,b);c[e]=f}return c};var kk=function(a){this.index=a};kk.prototype.resolve=function(a,b){var c=Eg[this.index];if(c&&!b(c)){var d=c[Pa];if(a){if(a.get(d))return;a.set(d,!0)}c=Hg(c,a,b);a&&a.set(d,!1);return If(c)}};
var _M=function(a){return new kk(a)},lk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Hg(ek[a[f]],b,c);g===eb&&(e=!0);d.push(g)}return e?new ob(d):d.join("")}},_T=function(a){return new lk(arguments)},mk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Hg(a[0],c,d);if(a[0]instanceof kk&&b(8)&&b(16)){if(e===eb)return e;var f=ya();gk.set(f,e);return'google_tag_manager["GTM-TP5WBG"].macro(\''+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=Ij[a[g]](e);return e}},_E=function(a,b){return new mk(arguments)},nk=function(a,b){this.w=a;this.na=b},_R=function(a,b){return new nk(a,b)};
var Hg=function(a,b,c){var d=a;if(a instanceof kk||a instanceof jk||a instanceof lk||a instanceof mk)return a.resolve(b,c);if(!(a instanceof nk))if(cb(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Hg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Hg(a[f],b,c))}return d},qk=function(){for(var a=[_cn,_u,'url hostname','host',_M(0),'feiniu.com',_e,'event',_M(1),'gtm.dom',_re,'_event',_M(2),'.*','1224079_2',_sp,true,'975365758',_v,'google_tag_params',2,_M(3),1,_ua,_c,'UID','UA-46390714-1',_M(4),false,'allowLinker','false',{29:30},'\x26tid',{32:27,29:30},'url',_M(5),'buy.feiniu.com/pay/finish','1224079_4','1224079_3',_awct,'972799902','LtadCLqB1AgQnv_uzwM','',3,'url path','path',_f,'referrer','element','gtm.element','element classes','gtm.elementClasses','element id','gtm.elementId','element target','gtm.elementTarget',_et,'element text','element url','gtm.elementUrl','history new url fragment','gtm.newUrlFragment','history old url fragment','gtm.oldUrlFragment','history new state','gtm.newHistoryState','history old state','gtm.oldHistoryState','history change source','gtm.historyChangeSource','google_conversion_id'],b=[],c=0;c<a.length;c++)b[c]=
pk(c,a);return b},pk=function(a,b){var c=b[a],d=c;if(c instanceof kk||c instanceof mk||c instanceof lk||c instanceof nk)d=c;else if(cb(c)){d=[];for(var e=0;e<c.length;e++)d[e]=pk(c[e],b)}else if("object"==typeof c){d=new jk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],pk(c[f],b))}return d},sk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
ek[e[1]]);if(1==a){var f=rk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=fk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=rk(e[g]);3==a&&(c[d]=ek[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=ek[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},rk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<dk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},tk=function(a,b,c){a.push.apply(a,sk(b,c))};var uk;
var Gg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=xk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},Ak=function(a){},Bk=function(a,b){},Jg=function(a){};var Ck,Dk;
var Pk=function(a){return function(){}},Qk=function(a){return function(){}};var Rk=function(a){var b=this;this.h=a;this.ca=this.rb=!1;this.xa=[];this.ua=[];this.X=function(){b.ca||Of(b.xa);Rf(b,1);if(Eb[a])for(var c=0;c<Eb[a].length;c++)Eb[a].shift().X()};this.W=function(){b.ca||Of(b.ua);Rf(b,2);if(Eb[a])for(var c=0;c<Eb[a].length;c++)Eb[a].shift().W()};this.C=qb},Sk=function(a,b){a.xa.push(b)},Tk=function(a,b){a.ua.push(b)},Uk=function(a){this.K=[];this.Sa=[];this.gb={};this.mb=[];this.V=0;this.Qa={};this.Ua={};this.Ta={};this.event=a};Uk.prototype.addListener=function(a){this.mb.push(a)};
var Vk=function(a){0<a.V||Of(a.mb)},Wk=function(a,b,c,d,e,f){if(!c.ca){a.K[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=cb(d)?d.slice():["or",d];e=cb(e)?e.slice():[e];f=cb(f)?f.slice():[f];a.gb[b]=d;a.Qa[b]=0<e.length;a.Ua[b]=0<f.length;a.V++;var g=function(){0<a.V&&!a.Qa[b]&&!a.Ua[b]&&a.V--;Vk(a)};Sk(c,g);Tk(c,g)}},al=function(a){for(var b=[],c={},d=0;d<a.K.length;c={R:c.R},d++)if(c.R=a.K[d],c.R){var e=a.gb[d],f=a.Qa[d],g=a.Ua[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Xk(e,
c.R.C),k=0;k<e.length;k++)e[k]instanceof nk&&e[k].w!=d&&Yk(a,e[k].w,h);(f||g)&&Zk(a,d,function(a){return function(){0<a.R.B.V&&a.R.B.V--;Vk(a.R.B)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.K[b[d]].C();for(d=0;d<a.Sa.length;d++){var l=a.Sa[d];$k(l);0<l.length&&l[0].C()}},Yk=function(a,b,c){a.K[b]&&(Sk(a.K[b],function(){c(b,!0)}),Tk(a.K[b],function(){c(b,!1)}))},Xk=function(a,b){var c=qb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof nk&&a[h].w===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Zk=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=ik[b];if(a.event.f(h)){}else g=bl(h,b,a.event.f,a);if(c=g){var k=cl(b,!0);0<k.length&&f(k[0].w);d.push(c);var l=cl(b,!1);0<l.length&&f(l[0].w)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=cl(h.h,!0);if(0<k.length){var l=d[g-1],m=dl(h);Sk(l,m);0==k[0].na?Tk(l,m):Tk(l,c)}var n=cl(h.h,!1);0<n.length&&(m=dl(d[g+1]),Sk(h,m),0==n[0].na?Tk(h,m):Tk(h,c))}Sk(d[d.length-1],c);Tk(d[d.length-1],c);a.Sa.push(d)}},cl=function(a,b){var c=b?He:Ye,d=ik[a],e=void 0===d[c]?[]:d[c];return cb(e)?e:[e]},dl=function(a){return function(){a.C()}},$k=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.h,f=Db[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.B.Ta[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=cl(a[c+1].h,!0);if(0<h.length&&1==h[0].na)for(++c;c<a.length;c++)b.push(a[c])}}var k=el(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],v=p[0],x=p[p.length-1],r,A=0;A<a.length;A++){var C=a[A];!m&&C.h==v&&0<A&&(m=a[A-1]);C.h==x&&A<a.length-1&&(n=a[A+1]);if(-1<vb(p,C.h))if(r=a.splice(A,1)[0],C.h==x)break;else A--}if(r){var w=Number(l),y=m,J=n;if(y){var K=y.xa[0],E=y.ua[0],D=y;D.xa=[];D.ua=
[];Sk(y,K);Tk(y,E)}if(y&&J){var H=dl(J);Sk(y,H);var N=cl(y.h,!1);0<N.length&&N[0].w!=w&&0==N[0].na&&Tk(y,H);var L=cl(J.h,!0);0<L.length&&L[0].w!=w&&0==L[0].na&&Tk(y,H)}}}},el=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=cl(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=cl(a,!1);0<c.length&&f(c[0].w)};f(d.h);b[d.h]=e}fl(a,b);return b},fl=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].h,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<vb(b[e],d)){delete b[d];break}}};var gl=function(a,b,c){return function(){a[sd]=b.X;a[td]=b.W;var d=b.h,e=b.B&&b.B.Ta[d],f=Db[d]&&Db[d].state,g=e?void 0!==e:b.rb||b.ca,h=Db[d]&&Db[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Rf(b,0);var m=b.B?b.B.event:void 0,n=a;n=Hg(n,new Hf,c);a=n;if(m){}If(a,b.X,b.W)}else k&&0==f||l&&0==e?Eb[d].push(b):k&&1==f||l&&1==e?b.X():b.W()}},bl=function(a,b,c,d){var e=d&&d.K,f;if(f=e)a:{if(e&&cb(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].h===b){f=e[g];break a}f=void 0}var h=f||new Rk(b);h.B=d;Sk(h,Pk(a));Tk(h,Qk(a));h.C=gl(a,h,c);return h};var _sp=function(a,b,c){t("//www.googleadservices.com/pagead/conversion_async.js",function(){var d=B.google_trackConversion;T(d)?d({google_conversion_id:a[yd],google_conversion_label:a[Id],google_custom_params:a[Fc]||{},google_remarketing_only:!0,onload_callback:b})||c():c()},c)};_sp.a="sp";_sp.b=["google"];
var kl=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];B[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!za(b))return!1;for(var e=Aa(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;if(a[Xc]){c=Y("ecommerce");
}else a[Wc]&&(c=a[Wc].ecommerce);if(!za(c))return;c=Object(c);var e=Aa(a[od],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=
c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&x[e]||!c&&void 0===x[e])){var f=r[e]?Ca(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}La("GoogleAnalyticsObject",a[Yd]||"ga");var l=function(){return B.GoogleAnalyticsObject},m=La(l(),function(){var a=B[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(I());
var n="",p="";"string"!=typeof a[lf]?(p=ya(),n=p+"."):""!==a[lf]&&(p=a[lf],n=p+".");var v=!1;var x={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0},r={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,
nonInteraction:!0,useBeacon:!0};var A={name:p};k(a[od],A,!0);m("create",a[Gb],A);d("set","&gtm","GTM-TP5WBG");var C={};k(a[od],C,!1)&&d("set",C);var w;a[Nd]&&d("require","linkid","linkid.js");
d("set","hitCallback",function(){if(T(a[ud]))a[ud]();else{var c=a[od],d=c&&c.hitCallback;T(d)&&d()}b()});if(a[gf]){}else if(a[hf]){}else if(a[kf]){}else if(a[jf]){}else if(a[Nc]){}else if(a[Lc]){}else if(a[ff]){}else{a[dd]&&(d("require","ec","ec.js"),h());if(a[Vc]&&!a[fd]){var L="_dc_gtm_"+String(a[Gb]).replace(/[^A-Za-z0-9-]/g,
"");d("require","displayfeatures",void 0,{cookieName:L})}w?d("send","pageview",w):d("send","pageview");}if(!kl){var R=a[Jc]?"u/analytics_debug.js":"analytics.js";a[Dd]&&!a[Jc]&&(R="internal/"+R);kl=!0;t(O("https:","http:","//www.google-analytics.com/"+R,v),function(){B[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var ll=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=hk[b]&&Hg(hk[b],new Hf,c),e=d;d&&(e=Hj(d));a[b]=[e,d]}return a[b]}},ml=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.U(c[d],a.f)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.U(e[d],a.f)[0])return!1;return!0},nl=!1;
yg=function(a,b,c,d,e){switch(b){case "gtm.js":if(nl)return!1;nl=!0;break;case "gtm.sync":if(Y("gtm.snippet")!=Bb)return!1}for(var f={id:a,name:b,qa:d||qb,Ba:rk(),Na:rk(),U:ll(),f:Dg(c)},g=[],h=0;h<$g.length;h++)if(ml(f,$g[h])){g[h]=!0;for(var k=f,l=$g[h],m=l[1],n=0;n<m.length;n++)k.Ba[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Na[p[n]]=!0}else g[h]=!1;var L=[];for(var G=0;G<dk;G++)if(f.Ba[G]&&!f.Na[G])if(f.f(ik[G])){}else{L[G]=ik[G];}f.ka=L;for(var R=new Uk(f),M=0;M<dk;M++)if(f.Ba[M]&&!f.Na[M])if(f.f(ik[M])){}else{var U=f.ka[M],la=bl(U,M,f.f,R);Wk(R,M,la,U[Qc],U[He],U[Ye]);if(U[Fb])break}R.addListener(f.qa);al(R);Vk(R);e&&T(e)&&e({passingRules:g,resolvedTags:f.ka});if("gtm.js"==b||"gtm.sync"==b)a:{}for(var zc in f.ka)if(f.ka.hasOwnProperty(zc)){var Jf=
f.ka[zc],wd;if(!(wd=void 0==Jf[Pa])){var Kf=Jf[Pa];wd=!("function"!=typeof String.prototype.startsWith?0===Kf.indexOf("_implicit"):Kf.startsWith("_implicit"))}if(wd)return!0}return!1};var pl=function(){};var ql=function(){};var ol={macro:function(a){if(gk.contains(a))return gk.get(a)}};ol.dataLayer=ig;ol.onHtmlSuccess=Sh(!0);ol.onHtmlFailure=Sh(!1);ol.callback=function(a){Na.hasOwnProperty(a)&&T(Na[a])&&Na[a]();delete Na[a]};
ol.Ib=function(){var a=B.google_tag_manager;a||(a=B.google_tag_manager={});fb=a;if(a["GTM-TP5WBG"]){var b=fb.zones;b&&b.registerNatural("GTM-TP5WBG")}else{a["GTM-TP5WBG"]=ol;bh();ek.push.apply(ek,qk());tk(fk,0,"13:0,13:1,15:2,4:3,2:4,3:5,13:6,15:7,2:8,3:9,13:10,15:11,2:12,3:13,13:15,19:16,14:17,13:18,15:19,18:19,6:20,5:21,20:22,13:23,13:24,15:25,22:26,0:27,11:28,10:28,21:28,12:31,7:28,8:28,1:33,17:28,9:28,20:20,15:34,2:35,3:36,13:39,14:40,16:41,22:42,20:43,15:44,4:45,13:46,15:47,15:48,18:49,15:50,18:51,15:52,18:53,15:54,18:55,13:56,15:57,15:58,18:59,15:60,18:61,15:62,18:63,15:64,18:65,15:66,18:67,15:68,18:69,15:70,22:17");tk(Eg,1,"O,AD,Ah,AAgH,AAAAH,CAAAAAE,CAAAAAAw,AAAAAAAAD,AAgAAAAAM,AAgAAAAAw,AAgAAAAAAD,AAgAAAAAAM,AAAAAAAAAw,AAgAAAAAAAD,AAgAAAAAAAM,AAgAAAAAAAw,AAgAAAAAAAAD,AAgAAAAAAAAM,AAgAAAAAAAAw,AAAABAAAAAAAD");tk(hk,1,"x,BM,AQD,BAAAAAY");tk(ik,1,"AAcY,AAAg4_D,AAAAAAgP");tk($g,2,"H:D::,O:E::");tk(ah,4,"14.14:,38:");for(var c=0;c<ik.length;c++){var d=ik[c],
e=1;d[ee]?e=2:d[qf]&&(e=0);Db[c]={firingOption:e,state:void 0};Eb[c]=[]}ug();Mg();var n=B;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)Wf();else{Q(P,"DOMContentLoaded",Wf);Q(P,"readystatechange",Wf);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(A){}p&&Yf()}Q(n,"load",Wf)}"complete"===P.readyState?ag():Q(B,"load",ag);ql();pl();a:{}}};ol.Ib();var _vs="res_ts:1446804196582000,srv_cl:165981855,ds:live,cv:28";
})()
